live_config_reload=true

[window]
dynamic_padding=true
decorations="None"
opacity=0.7
decorations_theme_variant="None"

[scrolling]
history=10000
multiplier=2

[font]
normal={family="OverpassM Nerd Font Mono"}
size=8.5

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"

[mouse]
hide_when_typing=true
