github.com:
    users:
        rishibhargawa:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: rishibhargawa
