live_config_reload=true

import=[
	"~/.config/alacritty/themes/themes/aura.toml"
]

[window]
dynamic_padding=true
decorations="None"
opacity=0.6
decorations_theme_variant="None"

[scrolling]
history=10000
multiplier=1

[font]
normal={family="Lilex Nerd Font Mono",style="Medium"}
size=9

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"

[mouse]
hide_when_typing=true
