live_config_reload=true

import=[
	"~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[window]
dynamic_padding=true
decorations="None"
opacity=1
decorations_theme_variant="None"

[scrolling]
history=10000
multiplier=3

[font]
normal={family="Mononoki Nerd Font Mono"}
size=9

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"

[mouse]
hide_when_typing=true
