live_config_reload=true

[window]
dynamic_padding=true
decorations="None"
opacity=0.6
decorations_theme_variant="None"

[scrolling]
history=10000
multiplier=3

[font]
normal={family="FiraCode Nerd Font Mono",style="Regular"}
size=8

[selection]
save_to_clipboard=true

[terminal]
osc52="CopyPaste"

[mouse]
hide_when_typing=true
