live_config_reload=true
ipc_socket=true

[window]
dynamic_padding=true
decorations="None"
decorations_theme_variant="None"
opacity=0.8

[scrolling]
history=10000
multiplier=1

[font]
normal={family="JetBrainsMono Nerd Font Mono",style="Regular"}
bold={family="JetBrainsMono Nerd Font Mono",style="Bold"}
italic={family="JetBrainsMono Nerd Font Mono",style="Italic"}
bold_italic={family="JetBrainsMono Nerd Font Mono",style="Bold Italic"}
size=10

[selection]
save_to_clipboard=true

[cursor]
thickness=0.1

[terminal]
osc52="CopyPaste"

[mouse]
hide_when_typing=true
